version: '3'

services:
  tweet-server:
    build:
      context: .
      dockerfile: tweet-server/.Dockerfile
    ports:
      - "50051:50051"
  tweet-analysis-client:
    build:
      context: .
      dockerfile: tweet-analysis-client/.Dockerfile
    depends_on:
      - "tweet-server"
    command: ["./wait-for-it.sh", "tweet-server:50051", "--", "python", "tweet_analysis_client.py"]
  reddit-post-server:
    build:
      context: .
      dockerfile: reddit-post-server/.Dockerfile
    ports:
      - "50052:50052"
  reddit-analysis-client:
    build:
      context: .
      dockerfile: reddit-analysis-client/.Dockerfile
    depends_on:
      - "reddit-post-server"
    command: ["./wait-for-it.sh", "reddit-post-server:50052", "--", "python", "reddit_analysis_client.py"]
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  website:
    build:
      context: .
      dockerfile: website/.Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - "redis" 