apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-post-server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-post-server
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 10%
  template:
    metadata:
      labels:
        app: reddit-post-server
    spec:
      containers:
        - name: reddit-post-server
          image: matalt/reddit-post-server:latest
          ports:
            - containerPort: 50052
          resources:
            limits:
              cpu: "0.05"
            requests:
              cpu: "0.03"