apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tweet-server
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 10%
  template:
    metadata:
      labels:
        app: tweet-server
    spec:
      containers:
        - name: tweet-server
          image: matalt/tweet-server:latest
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: "0.05"
            requests:
              cpu: "0.04"