apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-analysis-client-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tweet-analysis-client
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 10%
  template:
    metadata:
      labels:
        app: tweet-analysis-client
    spec:
      containers:
        - name: tweet-analysis-client
          image: matalt/tweet-analysis-client:latest
          resources:
            limits:
              cpu: "0.125"
            requests:
              cpu: "0.1"